// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ONSdigital/go-ns/common (interfaces: RCHTTPClienter)

// Package mock_common is a generated GoMock package.
package mock_common

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	io "io"
	http "net/http"
	url "net/url"
	reflect "reflect"
	time "time"
)

// MockRCHTTPClienter is a mock of RCHTTPClienter interface
type MockRCHTTPClienter struct {
	ctrl     *gomock.Controller
	recorder *MockRCHTTPClienterMockRecorder
}

// MockRCHTTPClienterMockRecorder is the mock recorder for MockRCHTTPClienter
type MockRCHTTPClienterMockRecorder struct {
	mock *MockRCHTTPClienter
}

// NewMockRCHTTPClienter creates a new mock instance
func NewMockRCHTTPClienter(ctrl *gomock.Controller) *MockRCHTTPClienter {
	mock := &MockRCHTTPClienter{ctrl: ctrl}
	mock.recorder = &MockRCHTTPClienterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRCHTTPClienter) EXPECT() *MockRCHTTPClienterMockRecorder {
	return m.recorder
}

// Do mocks base method
func (m *MockRCHTTPClienter) Do(arg0 context.Context, arg1 *http.Request) (*http.Response, error) {
	ret := m.ctrl.Call(m, "Do", arg0, arg1)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do
func (mr *MockRCHTTPClienterMockRecorder) Do(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockRCHTTPClienter)(nil).Do), arg0, arg1)
}

// Get mocks base method
func (m *MockRCHTTPClienter) Get(arg0 context.Context, arg1 string) (*http.Response, error) {
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockRCHTTPClienterMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRCHTTPClienter)(nil).Get), arg0, arg1)
}

// GetMaxRetries mocks base method
func (m *MockRCHTTPClienter) GetMaxRetries() int {
	ret := m.ctrl.Call(m, "GetMaxRetries")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetMaxRetries indicates an expected call of GetMaxRetries
func (mr *MockRCHTTPClienterMockRecorder) GetMaxRetries() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxRetries", reflect.TypeOf((*MockRCHTTPClienter)(nil).GetMaxRetries))
}

// Head mocks base method
func (m *MockRCHTTPClienter) Head(arg0 context.Context, arg1 string) (*http.Response, error) {
	ret := m.ctrl.Call(m, "Head", arg0, arg1)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Head indicates an expected call of Head
func (mr *MockRCHTTPClienterMockRecorder) Head(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Head", reflect.TypeOf((*MockRCHTTPClienter)(nil).Head), arg0, arg1)
}

// Post mocks base method
func (m *MockRCHTTPClienter) Post(arg0 context.Context, arg1, arg2 string, arg3 io.Reader) (*http.Response, error) {
	ret := m.ctrl.Call(m, "Post", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post
func (mr *MockRCHTTPClienterMockRecorder) Post(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockRCHTTPClienter)(nil).Post), arg0, arg1, arg2, arg3)
}

// PostForm mocks base method
func (m *MockRCHTTPClienter) PostForm(arg0 context.Context, arg1 string, arg2 url.Values) (*http.Response, error) {
	ret := m.ctrl.Call(m, "PostForm", arg0, arg1, arg2)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostForm indicates an expected call of PostForm
func (mr *MockRCHTTPClienterMockRecorder) PostForm(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostForm", reflect.TypeOf((*MockRCHTTPClienter)(nil).PostForm), arg0, arg1, arg2)
}

// Put mocks base method
func (m *MockRCHTTPClienter) Put(arg0 context.Context, arg1, arg2 string, arg3 io.Reader) (*http.Response, error) {
	ret := m.ctrl.Call(m, "Put", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put
func (mr *MockRCHTTPClienterMockRecorder) Put(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockRCHTTPClienter)(nil).Put), arg0, arg1, arg2, arg3)
}

// SetAuthToken mocks base method
func (m *MockRCHTTPClienter) SetAuthToken(arg0 string) {
	m.ctrl.Call(m, "SetAuthToken", arg0)
}

// SetAuthToken indicates an expected call of SetAuthToken
func (mr *MockRCHTTPClienterMockRecorder) SetAuthToken(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAuthToken", reflect.TypeOf((*MockRCHTTPClienter)(nil).SetAuthToken), arg0)
}

// SetDownloadServiceToken mocks base method
func (m *MockRCHTTPClienter) SetDownloadServiceToken(arg0 string) {
	m.ctrl.Call(m, "SetDownloadServiceToken", arg0)
}

// SetDownloadServiceToken indicates an expected call of SetDownloadServiceToken
func (mr *MockRCHTTPClienterMockRecorder) SetDownloadServiceToken(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDownloadServiceToken", reflect.TypeOf((*MockRCHTTPClienter)(nil).SetDownloadServiceToken), arg0)
}

// SetFlorenceToken mocks base method
func (m *MockRCHTTPClienter) SetFlorenceToken(arg0 string) {
	m.ctrl.Call(m, "SetFlorenceToken", arg0)
}

// SetFlorenceToken indicates an expected call of SetFlorenceToken
func (mr *MockRCHTTPClienterMockRecorder) SetFlorenceToken(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFlorenceToken", reflect.TypeOf((*MockRCHTTPClienter)(nil).SetFlorenceToken), arg0)
}

// SetMaxRetries mocks base method
func (m *MockRCHTTPClienter) SetMaxRetries(arg0 int) {
	m.ctrl.Call(m, "SetMaxRetries", arg0)
}

// SetMaxRetries indicates an expected call of SetMaxRetries
func (mr *MockRCHTTPClienterMockRecorder) SetMaxRetries(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxRetries", reflect.TypeOf((*MockRCHTTPClienter)(nil).SetMaxRetries), arg0)
}

// SetTimeout mocks base method
func (m *MockRCHTTPClienter) SetTimeout(arg0 time.Duration) {
	m.ctrl.Call(m, "SetTimeout", arg0)
}

// SetTimeout indicates an expected call of SetTimeout
func (mr *MockRCHTTPClienterMockRecorder) SetTimeout(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTimeout", reflect.TypeOf((*MockRCHTTPClienter)(nil).SetTimeout), arg0)
}
