// Automatically generated by MockGen. DO NOT EDIT!
// Source: healthcheck.go

package healthcheck

import (
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockClient) EXPECT() *MockClientMockRecorder {
	return _m.recorder
}

// Healthcheck mocks base method
func (_m *MockClient) Healthcheck() (string, error) {
	ret := _m.ctrl.Call(_m, "Healthcheck")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Healthcheck indicates an expected call of Healthcheck
func (_mr *MockClientMockRecorder) Healthcheck() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Healthcheck")
}
