// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package identitytest

import (
	"context"
	"net/http"
	"sync"
)

var (
	lockHTTPClientMockDo sync.RWMutex
)

// HTTPClientMock is a mock implementation of HTTPClient.
//
//     func TestSomethingThatUsesHTTPClient(t *testing.T) {
//
//         // make and configure a mocked HTTPClient
//         mockedHTTPClient := &HTTPClientMock{
//             DoFunc: func(ctx context.Context, req *http.Request) (*http.Response, error) {
// 	               panic("TODO: mock out the Do method")
//             },
//         }
//
//         // TODO: use mockedHTTPClient in code that requires HTTPClient
//         //       and then make assertions.
//
//     }
type HTTPClientMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(ctx context.Context, req *http.Request) (*http.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *http.Request
		}
	}
}

// Do calls DoFunc.
func (mock *HTTPClientMock) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	if mock.DoFunc == nil {
		panic("moq: HTTPClientMock.DoFunc is nil but HTTPClient.Do was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *http.Request
	}{
		Ctx: ctx,
		Req: req,
	}
	lockHTTPClientMockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	lockHTTPClientMockDo.Unlock()
	return mock.DoFunc(ctx, req)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//     len(mockedHTTPClient.DoCalls())
func (mock *HTTPClientMock) DoCalls() []struct {
	Ctx context.Context
	Req *http.Request
} {
	var calls []struct {
		Ctx context.Context
		Req *http.Request
	}
	lockHTTPClientMockDo.RLock()
	calls = mock.calls.Do
	lockHTTPClientMockDo.RUnlock()
	return calls
}
